# Copyright 2025 The Secureblue Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: upstream-sync
permissions: {}
on:
  schedule:
    - cron: "00 2 * * *" # run daily at 2:00 UTC
  workflow_dispatch: # allow manually triggering sync

jobs:
  upstream-sync:
    name: Sync with upstream
    runs-on: ubuntu-24.04
    permissions:
      contents: write # Needed to modify repository contents

    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: true # zizmor: ignore[artipacked]
          fetch-depth: 0

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@e89d40939c28e39f97cf32126055eeae86ba74ec # v6.3.0
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_push_gpgsign: true
          
      - uses: webfactory/ssh-agent@a6f90b1f127823b31d4d4a8d96047790581349bd # v0.9.1
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Pull tags from upstream and rebase
        shell: bash
        env:
          FEDORA_VERSION: 42
        run: |
          set -euxo pipefail
          git config user.email '236124859+secureblue-bot@users.noreply.github.com'
          git config user.name 'secureblue-bot'
          git config --global user.signingkey E216FE5D67C3E057
          git config --global commit.gpgsign true
          git config --global tag.gpgSign true

          git remote add 'upstream' 'https://github.com/fedora-selinux/selinux-policy.git'
          git fetch --tags 'upstream'

          spec_url="https://src.fedoraproject.org/rpms/selinux-policy/raw/f${FEDORA_VERSION}/f/selinux-policy.spec"
          stable_commit=$(curl -Ls "${spec_url}" | grep -E '^%global commit [0-9a-fA-F]+$')
          stable_commit="${stable_commit#%global commit }"
          set +e
          git merge-base --is-ancestor "${stable_commit}" HEAD
          status=$?
          set -e
          case "${status}" in
          0) ;;
          1)
            git rebase "${stable_commit}"
            git push --follow-tags --force-with-lease
            ;;
          *) exit "${status}" ;;
          esac

          readarray -t merged_tags < <(git tag -l "v${FEDORA_VERSION}.*" --merged)
          git push origin "${merged_tags[@]}"
